import { JobAnalysis } from '../../types';

/**
 * One fictional job per pipeline stage, so the Kanban board and every
 * per-job screen (Rating, Tailored Application, Interview, Offer, Archive...)
 * has at least one populated card in the demo account. Companies and people
 * are invented — none of this is real.
 */
export const DEMO_JOBS: JobAnalysis[] = [
  {
    id: 'JOB-DEMO-01',
    createdAt: '2026-08-01T14:00:00.000Z',
    updatedAt: '2026-08-01T14:00:00.000Z',
    stage: 'Intake',
    companyName: 'Nimbus Robotics',
    roleTitle: 'Senior Product Manager, Platform',
    jobLink: 'https://example.com/jobs/nimbus-robotics-senior-pm',
    compensationRange: '$150k–$180k + equity',
    locationNotes: 'Remote (US)',
    jdText:
      'Nimbus Robotics is looking for a Senior Product Manager to own our platform APIs and developer experience.\n\nYou will partner with engineering leadership to define the roadmap for our public API surface, drive adoption among partner integrators, and own the metrics for developer activation and retention.\n\nRequirements:\n- 5+ years of B2B SaaS product management experience\n- Experience owning a platform or API product\n- Strong analytical skills, comfortable with SQL\n- Excellent written and verbal communication',
    recruiterNotes: 'Recruiter reached out on LinkedIn, referral from a former Meridian Cloudworks colleague.',
  },
  {
    id: 'JOB-DEMO-02',
    createdAt: '2026-07-20T14:00:00.000Z',
    updatedAt: '2026-07-21T09:00:00.000Z',
    stage: 'Parsed',
    companyName: 'Lattice Health',
    roleTitle: 'Product Manager, Clinician Tools',
    jobLink: 'https://example.com/jobs/lattice-health-pm-clinician-tools',
    compensationRange: '$140k–$165k',
    locationNotes: 'Hybrid — Denver, CO',
    jdText:
      'Lattice Health builds workflow software for outpatient clinics.\n\nWe are hiring a PM to own our clinician-facing scheduling and documentation tools, working closely with a team of 4 engineers and a designer.\n\nRequirements:\n- 4+ years of product management experience, healthcare a plus but not required\n- Track record of shipping complex B2B workflow software\n- Comfortable running discovery directly with end users',
    jdSegments: [
      { id: 'jd-0', text: 'Lattice Health builds workflow software for outpatient clinics.' },
      { id: 'jd-1', text: 'We are hiring a PM to own our clinician-facing scheduling and documentation tools, working closely with a team of 4 engineers and a designer.' },
      { id: 'jd-2', text: 'Requirements:\n- 4+ years of product management experience, healthcare a plus but not required\n- Track record of shipping complex B2B workflow software\n- Comfortable running discovery directly with end users' },
    ],
    parse: {
      company: 'Lattice Health',
      roleTitle: 'Product Manager, Clinician Tools',
      reportingLine: 'Reports to VP of Product',
      teamScope: '4 engineers, 1 designer',
      mustHaves: ['4+ years product management experience', 'Shipping complex B2B workflow software', 'Running discovery with end users'],
      niceToHaves: ['Healthcare domain experience'],
      strategicSignals: ['Clinician-facing workflow tools', 'Small dedicated pod ownership'],
      industryDomain: ['Healthcare', 'B2B SaaS'],
      stageSignals: ['Series B', 'Growth stage'],
      topCriticalSkills: ['Discovery with end users', 'Workflow software delivery'],
      hardGates: [],
    },
  },
  {
    id: 'JOB-DEMO-03',
    createdAt: '2026-07-10T14:00:00.000Z',
    updatedAt: '2026-07-12T10:00:00.000Z',
    stage: 'Rating',
    companyName: 'Solstice Analytics',
    roleTitle: 'Senior Product Manager, Self-Serve Analytics',
    jobLink: 'https://example.com/jobs/solstice-analytics-senior-pm',
    compensationRange: '$155k–$185k',
    locationNotes: 'Remote (US)',
    jdText:
      'Solstice Analytics is looking for a Senior PM to own our self-serve dashboard product end-to-end, from discovery through GA.\n\nRequirements:\n- 5+ years B2B SaaS product management\n- Direct experience launching a self-serve analytics or BI product\n- Strong SQL and experimentation background\n- Bachelor\'s degree required',
    jdSegments: [
      { id: 'jd-0', text: 'Solstice Analytics is looking for a Senior PM to own our self-serve dashboard product end-to-end, from discovery through GA.' },
      { id: 'jd-1', text: 'Requirements:\n- 5+ years B2B SaaS product management\n- Direct experience launching a self-serve analytics or BI product\n- Strong SQL and experimentation background\n- Bachelor\'s degree required' },
    ],
    parse: {
      company: 'Solstice Analytics',
      roleTitle: 'Senior Product Manager, Self-Serve Analytics',
      reportingLine: 'Reports to Director of Product',
      teamScope: '6 engineers, 2 designers',
      mustHaves: ['5+ years B2B SaaS PM experience', 'Launched a self-serve analytics/BI product', 'Strong SQL', 'Experimentation background'],
      niceToHaves: [],
      strategicSignals: ['End-to-end product ownership', 'GA launch experience'],
      industryDomain: ['B2B SaaS', 'Analytics'],
      stageSignals: ['Series C'],
      topCriticalSkills: ['Self-serve analytics launch experience', 'SQL'],
      hardGates: [{ category: 'Education', requirement: "Bachelor's degree required" }],
    },
    keywords: [
      {
        id: 'KW-DEMO-01',
        phrase: 'self-serve analytics launch',
        category: 'Critical skill',
        jdImportance: 'High',
        evidenceStatus: 'EVIDENCED',
        evidenceRefs: [{ type: 'deliverable', id: 'DEL-001' }],
        jdRefs: [{ segmentId: 'jd-0' }],
        whatCouldCount: 'Any 0-to-1 or GA launch of a self-serve or BI product.',
        recognitionPrompt: 'Have you launched a self-serve analytics or BI product from discovery to GA?',
        resumePriority: 'Lead bullet on the most recent role.',
        isTopCritical: true,
      },
    ],
    fitAnalysis: {
      roleScopeFit: { rating: 'Strong', rationale: 'Directly matches end-to-end ownership of a self-serve analytics product.' },
      industryDomainFit: { rating: 'Strong', rationale: 'Current role is the same product category at a similar company stage.' },
      seniorityStageFit: { rating: 'Strong', rationale: 'Senior PM title and scope align with 9 years of experience.' },
      technicalAiFit: { rating: 'Moderate', rationale: 'SQL experience is intermediate, not expert — worth a light gap flag.' },
      overallVerdict: 'PASS',
      rationale: 'Strong alignment on domain, scope, and seniority; the self-serve analytics launch at Meridian Cloudworks is a near-exact match.',
      leadWith: [{ text: 'Self-serve analytics launch to $4M ARR in 18 months', evidenceRefs: [{ type: 'deliverable', id: 'DEL-001' }] }],
      gaps: [{ text: 'SQL proficiency is intermediate rather than expert', evidenceRefs: [{ type: 'skill', id: 'SK-005' }] }],
    },
    hardGateAudit: {
      overallVerdict: 'CLEAR TO APPLY',
      gates: [
        {
          category: 'Education',
          requirement: "Bachelor's degree required",
          verdict: 'CLEAR',
          reason: 'B.S. Business Administration from Colorado State University satisfies this gate.',
          suggestedAction: 'None needed.',
          evidenceRefs: [{ type: 'education', id: 'EDU-001' }],
        },
      ],
    },
  },
  {
    id: 'JOB-DEMO-04',
    createdAt: '2026-06-28T14:00:00.000Z',
    updatedAt: '2026-07-02T11:00:00.000Z',
    stage: 'Tailored Application',
    companyName: 'Brightline Freight',
    roleTitle: 'Product Manager, Dispatch Platform',
    jobLink: 'https://example.com/jobs/brightline-freight-pm-dispatch',
    compensationRange: '$135k–$160k',
    locationNotes: 'Austin, TX (Hybrid)',
    jdText:
      'Brightline Freight needs a PM to modernize our dispatcher tooling.\n\nRequirements:\n- 3+ years product management experience\n- Experience with internal/operational tooling\n- Logistics domain experience a plus',
    jdSegments: [
      { id: 'jd-0', text: 'Brightline Freight needs a PM to modernize our dispatcher tooling.' },
      { id: 'jd-1', text: 'Requirements:\n- 3+ years product management experience\n- Experience with internal/operational tooling\n- Logistics domain experience a plus' },
    ],
    ratingFinalizedAt: '2026-07-01T16:00:00.000Z',
    parse: {
      company: 'Brightline Freight',
      roleTitle: 'Product Manager, Dispatch Platform',
      reportingLine: 'Reports to Head of Product',
      teamScope: '5 engineers',
      mustHaves: ['3+ years product management experience', 'Internal/operational tooling experience'],
      niceToHaves: ['Logistics domain experience'],
      strategicSignals: ['Legacy tool modernization'],
      industryDomain: ['Logistics'],
      stageSignals: ['Series B'],
      topCriticalSkills: ['Operational tooling delivery'],
      hardGates: [],
    },
    fitAnalysis: {
      roleScopeFit: { rating: 'Strong', rationale: 'Near-identical to the dispatch tooling rebuild at Fernbank Logistics.' },
      industryDomainFit: { rating: 'Strong', rationale: 'Direct logistics domain experience.' },
      seniorityStageFit: { rating: 'Strong', rationale: 'Scope matches prior PM-level ownership.' },
      technicalAiFit: { rating: 'Strong', rationale: 'No technical gaps identified.' },
      overallVerdict: 'PASS',
      rationale: 'Direct domain and scope match to a prior role.',
      leadWith: [{ text: 'Rebuilt dispatch tooling with real-time routing, cutting dispatch time 35%', evidenceRefs: [{ type: 'deliverable', id: 'DEL-003' }] }],
      gaps: [],
    },
    hardGateAudit: { overallVerdict: 'CLEAR TO APPLY', gates: [] },
    resumeStrategy: {
      outputBasename: 'Jordan_Rivera_Brightline_Freight_PM',
      headerTagline: 'Product Manager — Operational Tooling & Logistics',
      executiveSummary: 'Product leader with direct experience modernizing dispatcher tooling and shipping internal operational software at scale.',
      selectedOutcomes: ['Cut dispatch time 35% with a real-time routing engine rebuild', 'Saved ~1,200 dispatcher-hours per month'],
      roleStrategies: [{ company: 'Fernbank Logistics', titleReframe: 'Product Manager, Dispatch Platform', note: 'Lead with the dispatch tooling rebuild — it is the closest analog to this role.' }],
      skillRows: [{ label: 'Operational Tooling', content: 'Internal tool delivery, real-time systems, dispatcher workflows' }],
      keywordPlacement: [{ category: 'Critical skill', keywords: ['dispatcher tooling', 'operational tooling'] }],
      cautionClaims: [],
    },
    resume: {
      name: 'Jordan Rivera',
      contactInfo: 'jordan.rivera@example.com · 555-010-2938 · Denver, CO',
      summary: 'Product leader with direct experience modernizing dispatcher tooling and shipping internal operational software at scale.',
      skills: [{ category: 'Operational Tooling', terms: 'Internal tool delivery, real-time systems, dispatcher workflows' }],
      experience: [
        {
          company: 'Fernbank Logistics',
          companyDescriptor: 'Freight logistics company',
          title: 'Product Manager, Dispatch Platform',
          dates: 'Jun 2018 – Feb 2022',
          location: 'Austin, TX',
          bullets: [
            { text: 'Rebuilt the dispatch assignment tool with a real-time routing engine, cutting average dispatch time 35% and saving ~1,200 dispatcher-hours per month.', evidenceRefs: [{ type: 'deliverable', id: 'DEL-003' }] },
          ],
        },
      ],
      education: [{ institution: 'Colorado State University', degree: 'B.S. Business Administration', graduationDate: '2015' }],
    },
    keywordCoverage: {
      score: 92,
      threshold: 80,
      passed: true,
      criticalSkillCoverage: [{ phrase: 'dispatcher tooling', present: true }],
      secondaryKeywordCoverage: [{ phrase: 'logistics', present: true }],
      missingKeywords: [],
      unsupportedKeywords: [],
    },
  },
  {
    id: 'JOB-DEMO-05',
    createdAt: '2026-06-15T14:00:00.000Z',
    updatedAt: '2026-06-20T11:00:00.000Z',
    stage: 'Apply',
    companyName: 'Cascade Retail',
    roleTitle: 'Senior Product Manager, Checkout',
    jobLink: 'https://example.com/jobs/cascade-retail-senior-pm-checkout',
    compensationRange: '$145k–$170k',
    locationNotes: 'Remote (US)',
    jdText: 'Cascade Retail is hiring a Senior PM to own checkout conversion and experimentation.',
    ratingFinalizedAt: '2026-06-17T10:00:00.000Z',
    appliedAt: '2026-06-20T11:00:00.000Z',
    applicationMethod: 'Company careers portal',
    parse: {
      company: 'Cascade Retail',
      roleTitle: 'Senior Product Manager, Checkout',
      reportingLine: 'Reports to Director of Product',
      teamScope: '4 engineers',
      mustHaves: ['Experimentation experience', 'E-commerce checkout experience'],
      niceToHaves: [],
      strategicSignals: ['Conversion optimization'],
      industryDomain: ['E-commerce'],
      stageSignals: ['Public company'],
      topCriticalSkills: ['A/B testing', 'Checkout funnel optimization'],
      hardGates: [],
    },
    coverLetter: {
      content:
        'Dear Cascade Retail team,\n\nI ran 20+ A/B tests on a checkout flow early in my career, improving conversion by 9 points cumulatively — I\'d love to bring that same experimentation rigor to your checkout team.\n\nBest,\nJordan Rivera',
      wordCount: 42,
      approvalStatus: 'Approved',
    },
  },
  {
    id: 'JOB-DEMO-06',
    createdAt: '2026-05-20T14:00:00.000Z',
    updatedAt: '2026-08-05T15:00:00.000Z',
    stage: 'Interview',
    companyName: 'Meridian Systems',
    roleTitle: 'Group Product Manager, Platform',
    jobLink: 'https://example.com/jobs/meridian-systems-gpm-platform',
    compensationRange: '$175k–$210k',
    locationNotes: 'Remote (US)',
    jdText: 'Meridian Systems is hiring a Group PM to lead our platform team of 3 PMs.',
    ratingFinalizedAt: '2026-05-25T10:00:00.000Z',
    appliedAt: '2026-05-28T09:00:00.000Z',
    applicationMethod: 'Referral',
    parse: {
      company: 'Meridian Systems',
      roleTitle: 'Group Product Manager, Platform',
      reportingLine: 'Reports to VP of Product',
      teamScope: '3 PMs, 14 engineers',
      mustHaves: ['People management experience', 'Platform product experience'],
      niceToHaves: [],
      strategicSignals: ['Team leadership'],
      industryDomain: ['B2B SaaS'],
      stageSignals: ['Series D'],
      topCriticalSkills: ['Team leadership', 'Platform strategy'],
      hardGates: [],
    },
    interviews: [
      {
        id: 'ROUND-DEMO-01',
        roundName: 'Recruiter Screen',
        interviewerName: 'Sam Okafor',
        interviewerTitle: 'Technical Recruiter',
        format: 'Phone',
        scheduledAt: '2026-06-05T17:00:00.000Z',
        outcome: 'Passed',
        notes: 'Standard screen, discussed comp range and timeline.',
      },
      {
        id: 'ROUND-DEMO-02',
        roundName: 'Hiring Manager Interview',
        interviewerName: 'Priya Nandakumar',
        interviewerTitle: 'VP of Product',
        format: 'Video',
        scheduledAt: '2026-08-18T16:00:00.000Z',
        outcome: 'Scheduled',
        notes: 'Focus on team leadership and platform strategy.',
        prep: {
          likelyQuestions: [
            { question: 'Tell me about a time you led a team through a major re-platform.', why: 'Tests direct evidence of team leadership at platform scale.' },
          ],
          meetingGoal: 'Demonstrate platform-scale leadership and get clarity on team structure.',
          talkingPoints: ['Grew the analytics product team from 3 to 11', 'Led the self-serve analytics launch end-to-end'],
          generatedAt: '2026-08-10T12:00:00.000Z',
        },
      },
    ],
  },
  {
    id: 'JOB-DEMO-07',
    createdAt: '2026-04-01T14:00:00.000Z',
    updatedAt: '2026-08-08T09:00:00.000Z',
    stage: 'Offer',
    companyName: 'Anchorpoint Financial',
    roleTitle: 'Senior Product Manager, Platform',
    jobLink: 'https://example.com/jobs/anchorpoint-financial-senior-pm',
    compensationRange: '$160k–$190k',
    locationNotes: 'Remote (US)',
    jdText: 'Anchorpoint Financial is hiring a Senior PM for our internal platform team.',
    ratingFinalizedAt: '2026-04-05T10:00:00.000Z',
    appliedAt: '2026-04-08T09:00:00.000Z',
    applicationMethod: 'Company careers portal',
    parse: {
      company: 'Anchorpoint Financial',
      roleTitle: 'Senior Product Manager, Platform',
      reportingLine: 'Reports to Director of Product',
      teamScope: '8 engineers',
      mustHaves: ['5+ years product management experience'],
      niceToHaves: ['Fintech experience'],
      strategicSignals: ['Platform ownership'],
      industryDomain: ['Fintech'],
      stageSignals: ['Series C'],
      topCriticalSkills: ['Platform strategy'],
      hardGates: [],
    },
    interviews: [
      { id: 'ROUND-DEMO-03', roundName: 'Recruiter Screen', format: 'Phone', outcome: 'Passed', scheduledAt: '2026-04-15T17:00:00.000Z' },
      { id: 'ROUND-DEMO-04', roundName: 'Onsite Loop', format: 'Onsite', outcome: 'Passed', scheduledAt: '2026-05-10T15:00:00.000Z' },
    ],
    offer: {
      baseSalary: '$178,000',
      bonusTarget: '10%',
      variableComp: '',
      equity: { type: 'RSU', amount: '$60,000 over 4 years', vestingSchedule: '25% after year 1, then monthly' },
      benefitsNotes: 'Standard health/dental/vision, 4 weeks PTO.',
      otherTerms: '',
      startDate: '2026-09-15',
      decisionDeadline: '2026-08-22',
      receivedAt: '2026-08-08T09:00:00.000Z',
      guidance: {
        askAbout: ['Refresh grant timing', 'Remote work policy stability'],
        avoidAsking: ['Nothing off-limits identified'],
        negotiationAngles: ['Competing process at Meridian Systems is a credible lever for base salary'],
        redFlags: [],
      },
    },
  },
  {
    id: 'JOB-DEMO-08',
    createdAt: '2026-03-01T14:00:00.000Z',
    updatedAt: '2026-04-10T14:00:00.000Z',
    stage: 'Archive',
    companyName: 'Outrider Logistics',
    roleTitle: 'Product Manager, Fleet Ops',
    jobLink: 'https://example.com/jobs/outrider-logistics-pm-fleet-ops',
    compensationRange: '$130k–$155k',
    locationNotes: 'Remote (US)',
    jdText: 'Outrider Logistics is hiring a PM for our fleet operations tooling.',
    ratingFinalizedAt: '2026-03-05T10:00:00.000Z',
    appliedAt: '2026-03-08T09:00:00.000Z',
    applicationMethod: 'Company careers portal',
    interviews: [
      { id: 'ROUND-DEMO-05', roundName: 'Recruiter Screen', format: 'Phone', outcome: 'Passed', scheduledAt: '2026-03-15T17:00:00.000Z' },
      { id: 'ROUND-DEMO-06', roundName: 'Hiring Manager Interview', format: 'Video', outcome: 'Rejected', scheduledAt: '2026-03-25T16:00:00.000Z', notes: 'Team decided to prioritize a candidate with deeper fleet/telematics background.' },
    ],
    archivedAt: '2026-04-10T14:00:00.000Z',
    archivedFromStage: 'Interview',
    archiveReason: 'Rejected',
    archiveNotes: 'Good process, lost to a candidate with direct telematics experience.',
  },
];
