import { JobMatch } from '../../types';

/** Fictional Job Matches for the demo account, covering every MatchStatus. */
export const DEMO_MATCHES: JobMatch[] = [
  {
    id: 'MATCH-DEMO-01',
    createdAt: '2026-08-11T09:00:00.000Z',
    updatedAt: '2026-08-11T09:00:00.000Z',
    source: 'greenhouse',
    externalId: 'gh-nimbus-4471',
    sourceUrl: 'https://boards.greenhouse.io/nimbusrobotics/jobs/4471',
    companyName: 'Nimbus Robotics',
    roleTitle: 'Senior Product Manager, Platform',
    jdText: 'Nimbus Robotics is looking for a Senior Product Manager to own our platform APIs and developer experience.',
    status: 'New',
    matchScore: 78,
    verdict: 'PASS',
    hardGateRisk: 'CLEAR TO APPLY',
    topGaps: ['No direct API/developer-platform experience'],
    leadWith: ['Self-serve analytics launch to $4M ARR'],
  },
  {
    id: 'MATCH-DEMO-02',
    createdAt: '2026-08-10T09:00:00.000Z',
    updatedAt: '2026-08-10T09:00:00.000Z',
    source: 'lever',
    externalId: 'lv-latticehealth-2201',
    sourceUrl: 'https://jobs.lever.co/latticehealth/2201',
    companyName: 'Lattice Health',
    roleTitle: 'Product Manager, Clinician Tools',
    jdText: 'Lattice Health builds workflow software for outpatient clinics.',
    status: 'New',
    matchScore: 61,
    verdict: 'BORDERLINE',
    hardGateRisk: 'VERIFY FIRST',
    topGaps: ['No healthcare domain experience'],
    leadWith: ['Complex B2B workflow software delivery'],
  },
  {
    id: 'MATCH-DEMO-03',
    createdAt: '2026-07-09T09:00:00.000Z',
    updatedAt: '2026-07-12T10:00:00.000Z',
    source: 'manual-paste',
    companyName: 'Solstice Analytics',
    roleTitle: 'Senior Product Manager, Self-Serve Analytics',
    jdText: 'Solstice Analytics is looking for a Senior PM to own our self-serve dashboard product end-to-end, from discovery through GA.',
    status: 'Promoted',
    matchScore: 91,
    verdict: 'PASS',
    hardGateRisk: 'CLEAR TO APPLY',
    topGaps: [],
    leadWith: ['Self-serve analytics launch to $4M ARR'],
    promotedJobId: 'JOB-DEMO-03',
  },
  {
    id: 'MATCH-DEMO-04',
    createdAt: '2026-08-09T09:00:00.000Z',
    updatedAt: '2026-08-09T09:05:00.000Z',
    source: 'greenhouse',
    externalId: 'gh-vantage-9902',
    sourceUrl: 'https://boards.greenhouse.io/vantagecorp/jobs/9902',
    companyName: 'Vantage Corp',
    roleTitle: 'Product Manager, Sales Tools (Unpaid Trial Period)',
    jdText: 'Vantage Corp requires a 90-day unpaid trial period before full-time conversion.',
    status: 'Dismissed',
    dismissReason: "Auto-dismissed: JD matched excluded keyword 'unpaid'.",
  },
  {
    id: 'MATCH-DEMO-05',
    createdAt: '2026-08-07T09:00:00.000Z',
    updatedAt: '2026-08-07T09:00:00.000Z',
    source: 'lever',
    externalId: 'lv-outrider-3312',
    sourceUrl: 'https://jobs.lever.co/outriderlogistics/3312',
    companyName: 'Outrider Logistics',
    roleTitle: 'Associate Product Manager',
    jdText: 'Outrider Logistics is hiring an Associate PM for our fleet operations tooling.',
    status: 'Dismissed',
    matchScore: 22,
    verdict: 'SKIP',
    hardGateRisk: 'LIKELY AUTO-REJECT',
    topGaps: ['Role is a step down in seniority from current level'],
    leadWith: [],
  },
];
